// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNwqguvSEYChh-0caX6c3T6C9Zg4TTDU',
    appId: '1:886611316186:web:d9ffd39ebac9f23f2304e3',
    messagingSenderId: '886611316186',
    projectId: 'fir-2d055',
    authDomain: 'fir-2d055.firebaseapp.com',
    storageBucket: 'fir-2d055.appspot.com',
    measurementId: 'G-4G6DDLXRCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xwD5rm6kpQz4IftxSL__XONuJteneY4',
    appId: '1:886611316186:android:a017bccc862799152304e3',
    messagingSenderId: '886611316186',
    projectId: 'fir-2d055',
    storageBucket: 'fir-2d055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZvv8NvkMzRNwmYL-VzWZ0q64jav9RJc',
    appId: '1:886611316186:ios:6c105e9b01a3692e2304e3',
    messagingSenderId: '886611316186',
    projectId: 'fir-2d055',
    storageBucket: 'fir-2d055.appspot.com',
    iosBundleId: 'com.example.dealsdray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAZvv8NvkMzRNwmYL-VzWZ0q64jav9RJc',
    appId: '1:886611316186:ios:6c105e9b01a3692e2304e3',
    messagingSenderId: '886611316186',
    projectId: 'fir-2d055',
    storageBucket: 'fir-2d055.appspot.com',
    iosBundleId: 'com.example.dealsdray',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnNwqguvSEYChh-0caX6c3T6C9Zg4TTDU',
    appId: '1:886611316186:web:940cb8744bc2a99b2304e3',
    messagingSenderId: '886611316186',
    projectId: 'fir-2d055',
    authDomain: 'fir-2d055.firebaseapp.com',
    storageBucket: 'fir-2d055.appspot.com',
    measurementId: 'G-X2TETXQWKY',
  );
}
