// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1J0GTYzTAz_Jgk18KrDDHHd7a0kdp1ZY',
    appId: '1:550478642155:web:9032b071dedeb77031b7ae',
    messagingSenderId: '550478642155',
    projectId: 'geometric-vim-422815-b5',
    authDomain: 'geometric-vim-422815-b5.firebaseapp.com',
    databaseURL: 'https://geometric-vim-422815-b5-default-rtdb.firebaseio.com',
    storageBucket: 'geometric-vim-422815-b5.appspot.com',
    measurementId: 'G-F62V25SQ93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNQXyds844MifnWn3u5SFK9L2vqw_QAA',
    appId: '1:550478642155:android:87ef87ca4d7cd50c31b7ae',
    messagingSenderId: '550478642155',
    projectId: 'geometric-vim-422815-b5',
    databaseURL: 'https://geometric-vim-422815-b5-default-rtdb.firebaseio.com',
    storageBucket: 'geometric-vim-422815-b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjYzrTQqcbO6I5leCji64LQxMrYZQSXs',
    appId: '1:550478642155:ios:a6c5ab334448b74131b7ae',
    messagingSenderId: '550478642155',
    projectId: 'geometric-vim-422815-b5',
    databaseURL: 'https://geometric-vim-422815-b5-default-rtdb.firebaseio.com',
    storageBucket: 'geometric-vim-422815-b5.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjYzrTQqcbO6I5leCji64LQxMrYZQSXs',
    appId: '1:550478642155:ios:a6c5ab334448b74131b7ae',
    messagingSenderId: '550478642155',
    projectId: 'geometric-vim-422815-b5',
    databaseURL: 'https://geometric-vim-422815-b5-default-rtdb.firebaseio.com',
    storageBucket: 'geometric-vim-422815-b5.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1J0GTYzTAz_Jgk18KrDDHHd7a0kdp1ZY',
    appId: '1:550478642155:web:cfed35b14411874431b7ae',
    messagingSenderId: '550478642155',
    projectId: 'geometric-vim-422815-b5',
    authDomain: 'geometric-vim-422815-b5.firebaseapp.com',
    databaseURL: 'https://geometric-vim-422815-b5-default-rtdb.firebaseio.com',
    storageBucket: 'geometric-vim-422815-b5.appspot.com',
    measurementId: 'G-W32Q68D3CY',
  );

}